var OX_33f6cf9d = '';
OX_33f6cf9d += "<"+"div id=\"cdawrap\" style=\"display: none;\">\n";
OX_33f6cf9d += "<"+"a href=\"https://servedby.revive-adserver.net/ck.php?oaparams=2__bannerid=596__zoneid=470__cb=1a4167af6d__oadest=http%3A%2F%2Fgo.thoughtleaders.io%2F1190920190801\" class=\"carbon-img\"  rel=\"noopener\"target=\"_blank\">\n";
OX_33f6cf9d += "<"+"img src=\"https://tympanus.net/codrops/wp-content/banners/designdomain.jpg\" alt=\".design domain\" border=\"0\" height=\"100\" width=\"130\">\n";
OX_33f6cf9d += "<"+"/a>\n";
OX_33f6cf9d += "<"+"a href=\"https://servedby.revive-adserver.net/ck.php?oaparams=2__bannerid=596__zoneid=470__cb=1a4167af6d__oadest=http%3A%2F%2Fgo.thoughtleaders.io%2F1190920190801\" class=\"carbon-text\"  rel=\"noopener\"target=\"_blank\">Get a free .design domain name for a year. Comes with free whois privacy &amp; Site Builder Trial.<"+"/a>\n";
OX_33f6cf9d += "<"+"div class=\"cda-footer\">\n";
OX_33f6cf9d += "<"+"a class=\"carbon-poweredby\"href=\"https://servedby.revive-adserver.net/ck.php?oaparams=2__bannerid=596__zoneid=470__cb=1a4167af6d__oadest=https%3A%2F%2Ftympanus.net%2Fcodrops%2Fadvertise%2F\" rel=\"noopener\"target=\"_blank\">Become a sponsor<"+"/a>\n";
OX_33f6cf9d += "<"+"span class=\"cda-remove\" id=\"cda-remove\">Close<"+"/span>\n";
OX_33f6cf9d += "<"+"/div>\n";
OX_33f6cf9d += "<"+"script>\n";
OX_33f6cf9d += "setTimeout(function(){\n";
OX_33f6cf9d += "document.getElementById(\'cdawrap\').style.display = \'block\'; }, 1000);\n";
OX_33f6cf9d += "document.getElementById(\'cda-remove\').addEventListener(\'click\',function(e){\n";
OX_33f6cf9d += "document.getElementById(\'cdawrap\').style.display = \'none\';\n";
OX_33f6cf9d += "e.preventDefault();\n";
OX_33f6cf9d += "});\n";
OX_33f6cf9d += "<"+"/script>\n";
OX_33f6cf9d += "<"+"/div><"+"div id=\'beacon_1a4167af6d\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://servedby.revive-adserver.net/lg.php?bannerid=596&amp;campaignid=290&amp;zoneid=470&amp;loc=https%3A%2F%2Ftympanus.net%2FTutorials%2FCustomFileInputs%2F&amp;cb=1a4167af6d\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
document.write(OX_33f6cf9d);
